
postgresql: &postgresql
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *postgresql
  database: rupgo_development

test:
  <<: *postgresql
  database: rupgo_test

production:
  <<: *postgresql
  database: rupgo_production